<?xml version="1.0" encoding="utf-8"?>
<Database Name="FlowersPlanet" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ARTEMPC\SQLEXPRESS;Initial Catalog=FlowersPlanet;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FlowersPlanetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tag" Member="Tags">
    <Type Name="Tag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IdMenu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MetaKeys" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Article" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tag_FlowerInTag" Member="FlowerInTags" ThisKey="Id" OtherKey="IdTag" Type="FlowerInTag" />
      <Association Name="Menu_Tag" Member="Menu" ThisKey="IdMenu" OtherKey="Id" Type="Menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="MetaDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MetaKeys" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Article" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Menu_Tag" Member="Tags" ThisKey="Id" OtherKey="IdMenu" Type="Tag" />
    </Type>
  </Table>
  <Table Name="dbo.FlowerInTag" Member="FlowerInTags">
    <Type Name="FlowerInTag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdTag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdFlower" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tag_FlowerInTag" Member="Tag" ThisKey="IdTag" OtherKey="Id" Type="Tag" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Flower_FlowerInTag" Member="Flower" ThisKey="IdFlower" OtherKey="Id" Type="Flower" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Flower" Member="Flowers">
    <Type Name="Flower">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Article" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MetaDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MetaKeys" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Flower_FlowerInTag" Member="FlowerInTags" ThisKey="Id" OtherKey="IdFlower" Type="FlowerInTag" />
    </Type>
  </Table>
</Database>